---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-config-k8s-{{ .Values.clusterA.clusterName }}
spec:
  credentials:
    source: Secret
    secretRef:
      name: kubecontext-{{ .Values.clusterA.clusterName }}
      namespace: {{ .Values.common.crossplaneNamespace }}
      key: kubeconfig
