---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-config-helm-{{ .Values.clusterA.clusterName }}
spec:
  credentials:
    source: Secret
    secretRef:
      name: kubecontext-{{ .Values.clusterA.clusterName }}
      namespace: {{ .Values.common.crossplaneNamespace }}
      key: kubeconfig