---
apiVersion: eks.aws.upbound.io/v1beta1
kind: Addon
metadata:
  name: addon-eks-pod-identity-agent-{{ .Values.clusterB.clusterName }}
spec:
  forProvider:
    addonName: eks-pod-identity-agent
    region: {{ .Values.common.region }}
    clusterName: {{ .Values.clusterB.clusterName }}
  providerConfigRef:
    name: {{ .Values.common.providerConfigAWSName }}
