---
apiVersion: eks.aws.upbound.io/v1beta1
kind: ClusterAuth
metadata:
  name: cluster-auth-{{ .Values.clusterB.clusterName }}
spec:
  forProvider:
    region: {{ .Values.common.region }}
    clusterName: {{ .Values.clusterB.clusterName }}
  providerConfigRef:
    name: {{ .Values.common.providerConfigAWSName }}
  writeConnectionSecretToRef:
    namespace: {{ .Values.common.crossplaneNamespace }}
    name: kubecontext-{{ .Values.clusterB.clusterName }}
