apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-spock
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: teams/team-spock/dev 
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}

  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true